# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
display=d['k1'][3]['tricky'][3]['target'][3]
display

'hello'

# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10,dtype=int)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [15]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
x = np.arange(9)
x
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [19]:
import pandas as pd

In [20]:
d = {"Name":['koks','kavi','naf'],
     "Age":[20,21,22]}
d1=pd.DataFrame(d)
d1

   Name  Age
0  koks   20
1  kavi   21
2   naf   22

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [21]:
import datetime
start=datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
end=datetime.datetime.strptime("10-02-2023","%d-%m-%Y")
x=pd.date_range(start,end)
x

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [26]:
l1=pd.DataFrame(lists)
l1

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24